# Run as a script (cmake -P) at build time: turns migrations/NNNN_name.sql into
# a C++ source holding each file as a byte array, so the app needs no files on
# disk to create or upgrade its database.
#
#   -DMIGRATIONS_DIR=<dir> -DOUTPUT=<file.cpp>

if(NOT MIGRATIONS_DIR OR NOT OUTPUT)
    message(FATAL_ERROR "EmbedMigrations.cmake needs -DMIGRATIONS_DIR and -DOUTPUT")
endif()

file(GLOB _files LIST_DIRECTORIES false "${MIGRATIONS_DIR}/*.sql")
list(SORT _files)

set(_body "")
set(_table "")
set(_expected 1)
foreach(_f IN LISTS _files)
    get_filename_component(_name "${_f}" NAME)
    if(NOT _name MATCHES "^([0-9][0-9][0-9][0-9])_([a-z0-9_]+)\\.sql$")
        message(FATAL_ERROR "Migration '${_name}' is not named NNNN_lower_snake.sql")
    endif()
    math(EXPR _version "1${CMAKE_MATCH_1} - 10000")
    if(NOT _version EQUAL _expected)
        message(FATAL_ERROR "Migration '${_name}' breaks the sequence: expected version ${_expected}")
    endif()
    math(EXPR _expected "${_expected} + 1")
    file(READ "${_f}" _hex HEX)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
    string(APPEND _body "const unsigned char kSql${_version}[] = {${_bytes}0x00};\n")
    string(APPEND _table "    Migration{${_version}, \"${_name}\", std::string_view{reinterpret_cast<const char*>(kSql${_version}), sizeof(kSql${_version}) - 1}},\n")
endforeach()

if(_table STREQUAL "")
    message(FATAL_ERROR "No migrations found in ${MIGRATIONS_DIR}")
endif()

set(_content "// Generated by cmake/EmbedMigrations.cmake from migrations/*.sql. Do not edit.
#include \"spellbook/storage/migrations.hpp\"

namespace spellbook::storage
{
namespace
{
${_body}
// unsigned char, not char: a byte above 0x7F would be a narrowing error.
const Migration kMigrations[] = {
${_table}};
} // namespace

std::span<const Migration> embedded_migrations() noexcept
{
    return kMigrations;
}
} // namespace spellbook::storage
")

# Only rewrite when the content changed, so an unchanged tree does not recompile.
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" _old)
    if(_old STREQUAL _content)
        return()
    endif()
endif()
file(WRITE "${OUTPUT}" "${_content}")
